# Generated by F1-P21 payment execution basic.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment_requests", "0004_paymentrequest_paid_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("paid_at", models.DateField(verbose_name="fecha de pago")),
                ("paid_amount", models.DecimalField(decimal_places=2, max_digits=18, verbose_name="monto pagado")),
                ("bank_reference", models.CharField(max_length=120, verbose_name="referencia bancaria")),
                ("note", models.TextField(blank=True, verbose_name="observacion")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creado")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="actualizado")),
                ("executed_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_executions", to=settings.AUTH_USER_MODEL, verbose_name="ejecutado por")),
                ("payment_request", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="payment_execution", to="payment_requests.paymentrequest", verbose_name="solicitud de pago")),
            ],
            options={
                "verbose_name": "ejecucion de pago",
                "verbose_name_plural": "ejecuciones de pago",
                "ordering": ["-paid_at", "-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["paid_at"], name="payexec_paid_at_idx"),
                    models.Index(fields=["bank_reference"], name="payexec_bank_ref_idx"),
                ],
            },
        ),
    ]
