# Generated by F1-P21 payment execution basic.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_requests", "0003_alter_paymentrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("SUBMITTED", "Enviada"),
                    ("UNIT_REVIEW", "Revision unidad"),
                    ("FINANCE_REVIEW", "Revision finanzas"),
                    ("MANAGEMENT_REVIEW", "Revision gerencia"),
                    ("APPROVED", "Aprobada"),
                    ("PAID", "Pagada"),
                    ("REJECTED", "Rechazada"),
                    ("CANCELLED", "Cancelada"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="estado",
            ),
        ),
    ]
