# Generated by Django 5.0.6 on 2026-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0004_paymentrequest_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviada'), ('UNIT_REVIEW', 'Revisión unidad'), ('FINANCE_REVIEW', 'Revisión finanzas'), ('MANAGEMENT_REVIEW', 'Revisión gerencia'), ('APPROVED', 'Aprobada'), ('PAID', 'Pagada'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='estado'),
        ),
    ]
