# Generated by Django 5.0.6 on 2026-07-09 17:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_requests', '0005_alter_paymentrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='porcentaje')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='vigente desde')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'tasa de impuesto',
                'verbose_name_plural': 'tasas de impuesto',
                'ordering': ['-is_active', '-valid_from', 'name'],
            },
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='monto de impuesto'),
        ),
        migrations.CreateModel(
            name='PaymentRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descripción')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='precio unitario')),
                ('tax_percentage_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='porcentaje de impuesto aplicado')),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='monto de impuesto')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment_requests.paymentrequest', verbose_name='emisión')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_request_items', to='payment_requests.taxrate', verbose_name='tasa de impuesto')),
            ],
            options={
                'verbose_name': 'ítem de emisión',
                'verbose_name_plural': 'ítems de emisión',
                'ordering': ['id'],
            },
        ),
    ]
