# Generated by Django 5.0.6 on 2026-07-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentapprovalaction',
            name='action',
            field=models.CharField(choices=[('PAYMENT_EXECUTED', 'Pago ejecutado'), ('SUBMIT', 'Enviar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('CANCEL', 'Cancelar'), ('COMMENT', 'Comentario')], max_length=20, verbose_name='acción'),
        ),
    ]
