# Generated by Django 5.0.6 on 2026-07-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SOLICITANTE', 'Solicitante'), ('RESPONSABLE_UNIDAD', 'Responsable de unidad'), ('FINANZAS', 'Finanzas'), ('GERENCIA_GENERAL', 'Gerencia General'), ('JUNTA_DIRECTIVA', 'Junta Directiva'), ('CUENTAS_POR_PAGAR', 'Cuentas por Pagar'), ('AUDITOR', 'Auditor')], default='SOLICITANTE', max_length=40, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
