#!/usr/bin/env bash
set -euo pipefail

EXPECTED_BRANCH="feature/cross-action-audit"

echo "== F1-P23: Auditoría básica transversal de acciones críticas =="

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "ERROR: este directorio no parece ser un repositorio Git."
  exit 1
fi

cd "$(git rev-parse --show-toplevel)"

CURRENT_BRANCH="$(git branch --show-current)"
if [ "$CURRENT_BRANCH" != "$EXPECTED_BRANCH" ]; then
  echo "ERROR: rama incorrecta."
  echo "Actual:   $CURRENT_BRANCH"
  echo "Esperada: $EXPECTED_BRANCH"
  echo
  echo "Crea la rama con:"
  echo "  git switch develop"
  echo "  git pull origin develop"
  echo "  git switch -c $EXPECTED_BRANCH"
  exit 1
fi

echo "== Git status antes de aplicar cambios =="
git status --short

python3 - <<'PY'
from pathlib import Path

approval_models = Path("backend/apps/payment_approvals/models.py")
execution_models = Path("backend/apps/payment_execution/models.py")
detail_template = Path("backend/templates/payment_requests/paymentrequest_detail.html")
audit_tests = Path("backend/apps/payment_execution/tests/test_cross_action_audit.py")
migration_path = Path("backend/apps/payment_approvals/migrations/0002_paymentapprovalaction_payment_executed.py")

for p in [approval_models, execution_models, detail_template]:
    if not p.exists():
        raise SystemExit(f"ERROR: no existe {p}")

txt = approval_models.read_text()
if 'PAYMENT_EXECUTED = "PAYMENT_EXECUTED", "Pago ejecutado"' not in txt:
    txt = txt.replace(
        '    CANCEL = "CANCEL", "Cancelada"\n',
        '    CANCEL = "CANCEL", "Cancelada"\n    PAYMENT_EXECUTED = "PAYMENT_EXECUTED", "Pago ejecutado"\n',
        1,
    )
approval_models.write_text(txt)

migration_path.write_text("""# Generated by F1-P23 cross action audit.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentapprovalaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("SUBMIT", "Enviada"),
                    ("APPROVE", "Aprobada"),
                    ("REJECT", "Rechazada"),
                    ("RETURN", "Devuelta"),
                    ("CANCEL", "Cancelada"),
                    ("PAYMENT_EXECUTED", "Pago ejecutado"),
                ],
                max_length=30,
                verbose_name="acción",
            ),
        ),
    ]
""")

txt = execution_models.read_text()
if "PaymentApprovalAction" not in txt:
    txt = txt.replace(
        "from apps.payment_requests.models import PaymentRequest, PaymentRequestStatus\n",
        "from apps.payment_approvals.models import ApprovalActionType, PaymentApprovalAction\n"
        "from apps.payment_requests.models import PaymentRequest, PaymentRequestStatus\n",
        1,
    )

old = """    def save(self, *args, **kwargs):
        self.full_clean()
        result = super().save(*args, **kwargs)

        if self.payment_request.status != PaymentRequestStatus.PAID:
            self.payment_request.status = PaymentRequestStatus.PAID
            self.payment_request.save(update_fields=["status", "updated_at"])

        return result
"""
new = """    def save(self, *args, **kwargs):
        is_new = self.pk is None
        self.full_clean()
        result = super().save(*args, **kwargs)

        if self.payment_request.status != PaymentRequestStatus.PAID:
            self.payment_request.status = PaymentRequestStatus.PAID
            self.payment_request.save(update_fields=["status", "updated_at"])

        if is_new:
            PaymentApprovalAction.objects.create(
                payment_request=self.payment_request,
                action=ApprovalActionType.PAYMENT_EXECUTED,
                performed_by=self.executed_by,
                role=self.executed_by.role,
                comment=(
                    f"Pago ejecutado. Referencia bancaria: {self.bank_reference}. "
                    f"Monto pagado: {self.paid_amount}."
                ),
            )

        return result
"""
if old in txt:
    txt = txt.replace(old, new, 1)
elif "ApprovalActionType.PAYMENT_EXECUTED" not in txt:
    raise SystemExit("ERROR: no se encontró save esperado en PaymentExecution.")
execution_models.write_text(txt)

tpl = detail_template.read_text()
audit_block = """
<section>
  <h2>Historial de acciones críticas</h2>

  {% if approval_actions %}
    <table>
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Acción</th>
          <th>Usuario</th>
          <th>Rol</th>
          <th>Comentario</th>
        </tr>
      </thead>
      <tbody>
        {% for action in approval_actions %}
          <tr>
            <td>{{ action.created_at }}</td>
            <td>{{ action.get_action_display }}</td>
            <td>{{ action.performed_by }}</td>
            <td>{{ action.get_role_display }}</td>
            <td>{{ action.comment|default:"Sin comentario" }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No hay acciones críticas registradas.</p>
  {% endif %}
</section>
"""
if "Historial de acciones críticas" not in tpl:
    if "Ejecución de pago" in tpl:
        tpl = tpl.replace("<section>\n  <h2>Ejecución de pago</h2>", audit_block + "\n<section>\n  <h2>Ejecución de pago</h2>", 1)
    elif "{% endblock %}" in tpl:
        tpl = tpl.replace("{% endblock %}", audit_block + "\n{% endblock %}", 1)
    else:
        tpl += "\n" + audit_block
detail_template.write_text(tpl)

audit_tests.parent.mkdir(parents=True, exist_ok=True)
(audit_tests.parent / "__init__.py").touch(exist_ok=True)
audit_tests.write_text("""from datetime import date
from decimal import Decimal

from django.apps import apps
from django.contrib.auth import get_user_model
from django.test import TestCase
from django.urls import reverse

from apps.accounts.models import UserRole
from apps.payment_approvals.models import ApprovalActionType, PaymentApprovalAction
from apps.payment_execution.models import PaymentExecution
from apps.payment_requests.models import PaymentRequest, PaymentRequestStatus


_COUNTER = 0


def unique(prefix):
    global _COUNTER
    _COUNTER += 1
    return f"{prefix}-{_COUNTER}"


def required_data(model, **overrides):
    data = dict(overrides)
    for field in model._meta.concrete_fields:
        if field.name in data or field.primary_key or field.auto_created:
            continue
        if getattr(field, "auto_now", False) or getattr(field, "auto_now_add", False):
            continue
        if field.has_default() or field.null or field.blank:
            continue
        kind = field.get_internal_type()
        if kind in {"CharField", "TextField", "SlugField"}:
            value = unique(field.name)
            data[field.name] = value[: field.max_length] if getattr(field, "max_length", None) else value
        elif kind == "EmailField":
            data[field.name] = f"{unique('user')}@example.com"
        elif kind == "DecimalField":
            data[field.name] = Decimal("100.00")
        elif kind in {"IntegerField", "PositiveIntegerField", "PositiveSmallIntegerField"}:
            data[field.name] = 1
        elif kind == "BooleanField":
            data[field.name] = False
        elif kind == "DateField":
            data[field.name] = date.today()
    return data


def create_model(label, **overrides):
    app_label, model_name = label.split(".")
    model = apps.get_model(app_label, model_name)
    return model.objects.create(**required_data(model, **overrides))


class CrossActionAuditTests(TestCase):
    def setUp(self):
        self.company = create_model("organization.Company")
        self.beneficiary = create_model("beneficiaries.Beneficiary", company=self.company)
        self.requester = self.create_user("solicitante-audit@example.com", self.company, UserRole.SOLICITANTE)
        self.cxp_user = self.create_user("cxp-audit@example.com", self.company, UserRole.CUENTAS_POR_PAGAR)
        self.finance_user = self.create_user("finanzas-audit@example.com", self.company, UserRole.FINANZAS)

    def create_user(self, email, company, role):
        user_model = get_user_model()
        try:
            return user_model.objects.create_user(
                email=email,
                password="test-pass-123",
                primary_company=company,
                role=role,
            )
        except TypeError:
            user = user_model(email=email, primary_company=company, role=role)
            user.set_password("test-pass-123")
            user.save()
            return user

    def create_request(self, status=PaymentRequestStatus.APPROVED):
        return PaymentRequest.objects.create(
            company=self.company,
            beneficiary=self.beneficiary,
            requested_by=self.requester,
            amount=Decimal("320.00"),
            currency="VES",
            concept="Solicitud para auditoría transversal",
            due_date=date.today(),
            status=status,
        )

    def test_payment_execution_registers_cross_action_audit(self):
        payment_request = self.create_request()

        PaymentExecution.objects.create(
            payment_request=payment_request,
            executed_by=self.cxp_user,
            paid_at=date.today(),
            paid_amount=Decimal("320.00"),
            bank_reference="AUDIT-REF-001",
            note="Pago registrado para auditoría.",
        )

        action = PaymentApprovalAction.objects.get(
            payment_request=payment_request,
            action=ApprovalActionType.PAYMENT_EXECUTED,
        )

        self.assertEqual(action.performed_by, self.cxp_user)
        self.assertEqual(action.role, UserRole.CUENTAS_POR_PAGAR)
        self.assertIn("AUDIT-REF-001", action.comment)
        self.assertIn("320.00", action.comment)

    def test_detail_shows_cross_action_audit_history(self):
        payment_request = self.create_request()

        PaymentApprovalAction.objects.create(
            payment_request=payment_request,
            action=ApprovalActionType.SUBMIT,
            performed_by=self.requester,
            role=self.requester.role,
            comment="Solicitud enviada a aprobación.",
        )
        PaymentApprovalAction.objects.create(
            payment_request=payment_request,
            action=ApprovalActionType.APPROVE,
            performed_by=self.finance_user,
            role=self.finance_user.role,
            comment="Aprobación financiera.",
        )
        PaymentExecution.objects.create(
            payment_request=payment_request,
            executed_by=self.cxp_user,
            paid_at=date.today(),
            paid_amount=Decimal("320.00"),
            bank_reference="AUDIT-REF-002",
            note="Pago ejecutado.",
        )

        self.client.force_login(self.cxp_user)
        response = self.client.get(reverse("payment_requests:detail", kwargs={"pk": payment_request.pk}))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Historial de acciones críticas")
        self.assertContains(response, "Enviada")
        self.assertContains(response, "Aprobada")
        self.assertContains(response, "Pago ejecutado")
        self.assertContains(response, "Solicitud enviada a aprobación.")
        self.assertContains(response, "Aprobación financiera.")
        self.assertContains(response, "AUDIT-REF-002")
        self.assertContains(response, self.requester.email)
        self.assertContains(response, self.finance_user.email)
        self.assertContains(response, self.cxp_user.email)

    def test_detail_shows_empty_audit_history_message(self):
        payment_request = self.create_request()

        self.client.force_login(self.cxp_user)
        response = self.client.get(reverse("payment_requests:detail", kwargs={"pk": payment_request.pk}))

        self.assertEqual(response.status_code, 200)
        self.assertContains(response, "Historial de acciones críticas")
        self.assertContains(response, "No hay acciones críticas registradas.")
""")

print("OK: F1-P23 auditoría transversal aplicada correctamente.")
PY

echo "== Validación sintáctica Python de archivos tocados =="
python3 -m py_compile \
  backend/apps/payment_approvals/models.py \
  backend/apps/payment_approvals/migrations/0002_paymentapprovalaction_payment_executed.py \
  backend/apps/payment_execution/models.py \
  backend/apps/payment_execution/tests/test_cross_action_audit.py

echo "== Archivos modificados/creados =="
git status --short

cat <<'NEXT'

Siguiente paso obligatorio:

nordvpn disconnect
sleep 3

git status
git log --oneline --max-count=5

docker compose exec backend ruff check .
docker compose exec backend python manage.py check
docker compose exec backend python manage.py makemigrations --check --dry-run
docker compose exec backend python manage.py migrate
docker compose exec backend python manage.py test apps.organization apps.accounts apps.beneficiaries apps.payment_requests apps.payment_documents apps.payment_approvals apps.payment_execution

nordvpn connect United_States
nordvpn status

Si todo está correcto:

git add backend/apps/payment_approvals/models.py \
  backend/apps/payment_approvals/migrations/0002_paymentapprovalaction_payment_executed.py \
  backend/apps/payment_execution/models.py \
  backend/apps/payment_execution/tests/test_cross_action_audit.py \
  backend/templates/payment_requests/paymentrequest_detail.html \
  scripts/54_f1_p23_cross_action_audit.sh

git commit -m "feat: add cross action audit trail"
git push -u origin feature/cross-action-audit

NEXT
